// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ActiveUsersStat struct {
	Gauge     *Gauge   `json:"Gauge"`
	Trend     *Trend   `json:"Trend"`
	Sparkline []*Point `json:"Sparkline"`
}

type Gauge struct {
	Value *float64 `json:"value"`
}

type Point struct {
	Value *float64 `json:"value"`
	Time  *string  `json:"time"`
}

type Trend struct {
	Value *float64 `json:"value"`
}
